package com.mexc.dao.dao.common;

import com.laile.esf.common.util.Page;
import com.mexc.dao.dao.IBaseDAO;
import com.mexc.dao.model.common.TSysDict;
import com.mexc.dao.model.common.TSysDictExample;
import com.mexc.dao.model.member.MexcMemberAsset;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.math.BigDecimal;
import java.util.List;


@Repository
public interface TSysDictDao extends IBaseDAO<TSysDict,Integer> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_dict
     *
     * @mbggenerated Wed Mar 07 14:33:51 CST 2018
     */
    int countByExample(TSysDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_dict
     *
     * @mbggenerated Wed Mar 07 14:33:51 CST 2018
     */
    int deleteByExample(TSysDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_dict
     *
     * @mbggenerated Wed Mar 07 14:33:51 CST 2018
     */
    int insert(TSysDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_dict
     *
     * @mbggenerated Wed Mar 07 14:33:51 CST 2018
     */
    int insertSelective(TSysDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_dict
     *
     * @mbggenerated Wed Mar 07 14:33:51 CST 2018
     */
    List<TSysDict> selectByExample(TSysDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_dict
     *
     * @mbggenerated Wed Mar 07 14:33:51 CST 2018
     */
    int updateByExampleSelective(@Param("record") TSysDict record, @Param("example") TSysDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_dict
     *
     * @mbggenerated Wed Mar 07 14:33:51 CST 2018
     */
    int updateByExample(@Param("record") TSysDict record, @Param("example") TSysDictExample example);
}