delete from t_admin where id != 1;
delete from t_admin_role where id != 1;
delete from t_role where id != 1;
#truncate table t_file;
#truncate table t_mexc_address_lib;
truncate table t_mexc_address_mark;
truncate table t_mexc_asset_cash;
truncate table t_mexc_asset_recharge;
truncate table t_mexc_asset_trans;
truncate table t_mexc_entrust;
truncate table t_mexc_eth_cold_trans;
truncate table t_mexc_eth_hot_trans;
truncate table t_mexc_login_log;
#truncate table t_mexc_market_vcoin;
truncate table t_mexc_market_vcoin_collect;
truncate table t_mexc_member;
truncate table t_mexc_member_asset;
truncate table t_mexc_member_auth;
truncate table t_mexc_member_trans;
#truncate table t_mexc_plat_asset;
truncate table t_mexc_plat_asset_detail;
truncate table t_mexc_sys_recharge;
truncate table t_mexc_trade;
truncate table t_mexc_trade_detail;
truncate table t_mexc_activity;
truncate table t_mexc_activity_candies;
#truncate table t_mexc_vcoin;
#truncate table t_mexc_vcoin_fee;
