package com.mexc.dao.model.common;

import java.util.Date;

public class TSysDict {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_dict.dict_id
     *
     * @mbggenerated Wed Mar 07 14:33:51 CST 2018
     */
    private Integer dictId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_dict.dict_key
     *
     * @mbggenerated Wed Mar 07 14:33:51 CST 2018
     */
    private String dictKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_dict.dict_module
     *
     * @mbggenerated Wed Mar 07 14:33:51 CST 2018
     */
    private String dictModule;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_dict.dict_value
     *
     * @mbggenerated Wed Mar 07 14:33:51 CST 2018
     */
    private String dictValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_dict.dict_status
     *
     * @mbggenerated Wed Mar 07 14:33:51 CST 2018
     */
    private Integer dictStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_dict.dict_create_time
     *
     * @mbggenerated Wed Mar 07 14:33:51 CST 2018
     */
    private Date dictCreateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_dict.dict_id
     *
     * @return the value of t_sys_dict.dict_id
     *
     * @mbggenerated Wed Mar 07 14:33:51 CST 2018
     */
    public Integer getDictId() {
        return dictId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_dict.dict_id
     *
     * @param dictId the value for t_sys_dict.dict_id
     *
     * @mbggenerated Wed Mar 07 14:33:51 CST 2018
     */
    public void setDictId(Integer dictId) {
        this.dictId = dictId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_dict.dict_key
     *
     * @return the value of t_sys_dict.dict_key
     *
     * @mbggenerated Wed Mar 07 14:33:51 CST 2018
     */
    public String getDictKey() {
        return dictKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_dict.dict_key
     *
     * @param dictKey the value for t_sys_dict.dict_key
     *
     * @mbggenerated Wed Mar 07 14:33:51 CST 2018
     */
    public void setDictKey(String dictKey) {
        this.dictKey = dictKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_dict.dict_module
     *
     * @return the value of t_sys_dict.dict_module
     *
     * @mbggenerated Wed Mar 07 14:33:51 CST 2018
     */
    public String getDictModule() {
        return dictModule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_dict.dict_module
     *
     * @param dictModule the value for t_sys_dict.dict_module
     *
     * @mbggenerated Wed Mar 07 14:33:51 CST 2018
     */
    public void setDictModule(String dictModule) {
        this.dictModule = dictModule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_dict.dict_value
     *
     * @return the value of t_sys_dict.dict_value
     *
     * @mbggenerated Wed Mar 07 14:33:51 CST 2018
     */
    public String getDictValue() {
        return dictValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_dict.dict_value
     *
     * @param dictValue the value for t_sys_dict.dict_value
     *
     * @mbggenerated Wed Mar 07 14:33:51 CST 2018
     */
    public void setDictValue(String dictValue) {
        this.dictValue = dictValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_dict.dict_status
     *
     * @return the value of t_sys_dict.dict_status
     *
     * @mbggenerated Wed Mar 07 14:33:51 CST 2018
     */
    public Integer getDictStatus() {
        return dictStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_dict.dict_status
     *
     * @param dictStatus the value for t_sys_dict.dict_status
     *
     * @mbggenerated Wed Mar 07 14:33:51 CST 2018
     */
    public void setDictStatus(Integer dictStatus) {
        this.dictStatus = dictStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_dict.dict_create_time
     *
     * @return the value of t_sys_dict.dict_create_time
     *
     * @mbggenerated Wed Mar 07 14:33:51 CST 2018
     */
    public Date getDictCreateTime() {
        return dictCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_dict.dict_create_time
     *
     * @param dictCreateTime the value for t_sys_dict.dict_create_time
     *
     * @mbggenerated Wed Mar 07 14:33:51 CST 2018
     */
    public void setDictCreateTime(Date dictCreateTime) {
        this.dictCreateTime = dictCreateTime;
    }
}