package com.mexc.dao.model.common;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TSysDictExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_sys_dict
     *
     * @mbggenerated Wed Mar 07 14:33:51 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_sys_dict
     *
     * @mbggenerated Wed Mar 07 14:33:51 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_sys_dict
     *
     * @mbggenerated Wed Mar 07 14:33:51 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_dict
     *
     * @mbggenerated Wed Mar 07 14:33:51 CST 2018
     */
    public TSysDictExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_dict
     *
     * @mbggenerated Wed Mar 07 14:33:51 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_dict
     *
     * @mbggenerated Wed Mar 07 14:33:51 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_dict
     *
     * @mbggenerated Wed Mar 07 14:33:51 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_dict
     *
     * @mbggenerated Wed Mar 07 14:33:51 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_dict
     *
     * @mbggenerated Wed Mar 07 14:33:51 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_dict
     *
     * @mbggenerated Wed Mar 07 14:33:51 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_dict
     *
     * @mbggenerated Wed Mar 07 14:33:51 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_dict
     *
     * @mbggenerated Wed Mar 07 14:33:51 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_dict
     *
     * @mbggenerated Wed Mar 07 14:33:51 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_dict
     *
     * @mbggenerated Wed Mar 07 14:33:51 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_sys_dict
     *
     * @mbggenerated Wed Mar 07 14:33:51 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andDictIdIsNull() {
            addCriterion("dict_id is null");
            return (Criteria) this;
        }

        public Criteria andDictIdIsNotNull() {
            addCriterion("dict_id is not null");
            return (Criteria) this;
        }

        public Criteria andDictIdEqualTo(Integer value) {
            addCriterion("dict_id =", value, "dictId");
            return (Criteria) this;
        }

        public Criteria andDictIdNotEqualTo(Integer value) {
            addCriterion("dict_id <>", value, "dictId");
            return (Criteria) this;
        }

        public Criteria andDictIdGreaterThan(Integer value) {
            addCriterion("dict_id >", value, "dictId");
            return (Criteria) this;
        }

        public Criteria andDictIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("dict_id >=", value, "dictId");
            return (Criteria) this;
        }

        public Criteria andDictIdLessThan(Integer value) {
            addCriterion("dict_id <", value, "dictId");
            return (Criteria) this;
        }

        public Criteria andDictIdLessThanOrEqualTo(Integer value) {
            addCriterion("dict_id <=", value, "dictId");
            return (Criteria) this;
        }

        public Criteria andDictIdIn(List<Integer> values) {
            addCriterion("dict_id in", values, "dictId");
            return (Criteria) this;
        }

        public Criteria andDictIdNotIn(List<Integer> values) {
            addCriterion("dict_id not in", values, "dictId");
            return (Criteria) this;
        }

        public Criteria andDictIdBetween(Integer value1, Integer value2) {
            addCriterion("dict_id between", value1, value2, "dictId");
            return (Criteria) this;
        }

        public Criteria andDictIdNotBetween(Integer value1, Integer value2) {
            addCriterion("dict_id not between", value1, value2, "dictId");
            return (Criteria) this;
        }

        public Criteria andDictKeyIsNull() {
            addCriterion("dict_key is null");
            return (Criteria) this;
        }

        public Criteria andDictKeyIsNotNull() {
            addCriterion("dict_key is not null");
            return (Criteria) this;
        }

        public Criteria andDictKeyEqualTo(String value) {
            addCriterion("dict_key =", value, "dictKey");
            return (Criteria) this;
        }

        public Criteria andDictKeyNotEqualTo(String value) {
            addCriterion("dict_key <>", value, "dictKey");
            return (Criteria) this;
        }

        public Criteria andDictKeyGreaterThan(String value) {
            addCriterion("dict_key >", value, "dictKey");
            return (Criteria) this;
        }

        public Criteria andDictKeyGreaterThanOrEqualTo(String value) {
            addCriterion("dict_key >=", value, "dictKey");
            return (Criteria) this;
        }

        public Criteria andDictKeyLessThan(String value) {
            addCriterion("dict_key <", value, "dictKey");
            return (Criteria) this;
        }

        public Criteria andDictKeyLessThanOrEqualTo(String value) {
            addCriterion("dict_key <=", value, "dictKey");
            return (Criteria) this;
        }

        public Criteria andDictKeyLike(String value) {
            addCriterion("dict_key like", value, "dictKey");
            return (Criteria) this;
        }

        public Criteria andDictKeyNotLike(String value) {
            addCriterion("dict_key not like", value, "dictKey");
            return (Criteria) this;
        }

        public Criteria andDictKeyIn(List<String> values) {
            addCriterion("dict_key in", values, "dictKey");
            return (Criteria) this;
        }

        public Criteria andDictKeyNotIn(List<String> values) {
            addCriterion("dict_key not in", values, "dictKey");
            return (Criteria) this;
        }

        public Criteria andDictKeyBetween(String value1, String value2) {
            addCriterion("dict_key between", value1, value2, "dictKey");
            return (Criteria) this;
        }

        public Criteria andDictKeyNotBetween(String value1, String value2) {
            addCriterion("dict_key not between", value1, value2, "dictKey");
            return (Criteria) this;
        }

        public Criteria andDictModuleIsNull() {
            addCriterion("dict_module is null");
            return (Criteria) this;
        }

        public Criteria andDictModuleIsNotNull() {
            addCriterion("dict_module is not null");
            return (Criteria) this;
        }

        public Criteria andDictModuleEqualTo(String value) {
            addCriterion("dict_module =", value, "dictModule");
            return (Criteria) this;
        }

        public Criteria andDictModuleNotEqualTo(String value) {
            addCriterion("dict_module <>", value, "dictModule");
            return (Criteria) this;
        }

        public Criteria andDictModuleGreaterThan(String value) {
            addCriterion("dict_module >", value, "dictModule");
            return (Criteria) this;
        }

        public Criteria andDictModuleGreaterThanOrEqualTo(String value) {
            addCriterion("dict_module >=", value, "dictModule");
            return (Criteria) this;
        }

        public Criteria andDictModuleLessThan(String value) {
            addCriterion("dict_module <", value, "dictModule");
            return (Criteria) this;
        }

        public Criteria andDictModuleLessThanOrEqualTo(String value) {
            addCriterion("dict_module <=", value, "dictModule");
            return (Criteria) this;
        }

        public Criteria andDictModuleLike(String value) {
            addCriterion("dict_module like", value, "dictModule");
            return (Criteria) this;
        }

        public Criteria andDictModuleNotLike(String value) {
            addCriterion("dict_module not like", value, "dictModule");
            return (Criteria) this;
        }

        public Criteria andDictModuleIn(List<String> values) {
            addCriterion("dict_module in", values, "dictModule");
            return (Criteria) this;
        }

        public Criteria andDictModuleNotIn(List<String> values) {
            addCriterion("dict_module not in", values, "dictModule");
            return (Criteria) this;
        }

        public Criteria andDictModuleBetween(String value1, String value2) {
            addCriterion("dict_module between", value1, value2, "dictModule");
            return (Criteria) this;
        }

        public Criteria andDictModuleNotBetween(String value1, String value2) {
            addCriterion("dict_module not between", value1, value2, "dictModule");
            return (Criteria) this;
        }

        public Criteria andDictValueIsNull() {
            addCriterion("dict_value is null");
            return (Criteria) this;
        }

        public Criteria andDictValueIsNotNull() {
            addCriterion("dict_value is not null");
            return (Criteria) this;
        }

        public Criteria andDictValueEqualTo(String value) {
            addCriterion("dict_value =", value, "dictValue");
            return (Criteria) this;
        }

        public Criteria andDictValueNotEqualTo(String value) {
            addCriterion("dict_value <>", value, "dictValue");
            return (Criteria) this;
        }

        public Criteria andDictValueGreaterThan(String value) {
            addCriterion("dict_value >", value, "dictValue");
            return (Criteria) this;
        }

        public Criteria andDictValueGreaterThanOrEqualTo(String value) {
            addCriterion("dict_value >=", value, "dictValue");
            return (Criteria) this;
        }

        public Criteria andDictValueLessThan(String value) {
            addCriterion("dict_value <", value, "dictValue");
            return (Criteria) this;
        }

        public Criteria andDictValueLessThanOrEqualTo(String value) {
            addCriterion("dict_value <=", value, "dictValue");
            return (Criteria) this;
        }

        public Criteria andDictValueLike(String value) {
            addCriterion("dict_value like", value, "dictValue");
            return (Criteria) this;
        }

        public Criteria andDictValueNotLike(String value) {
            addCriterion("dict_value not like", value, "dictValue");
            return (Criteria) this;
        }

        public Criteria andDictValueIn(List<String> values) {
            addCriterion("dict_value in", values, "dictValue");
            return (Criteria) this;
        }

        public Criteria andDictValueNotIn(List<String> values) {
            addCriterion("dict_value not in", values, "dictValue");
            return (Criteria) this;
        }

        public Criteria andDictValueBetween(String value1, String value2) {
            addCriterion("dict_value between", value1, value2, "dictValue");
            return (Criteria) this;
        }

        public Criteria andDictValueNotBetween(String value1, String value2) {
            addCriterion("dict_value not between", value1, value2, "dictValue");
            return (Criteria) this;
        }

        public Criteria andDictStatusIsNull() {
            addCriterion("dict_status is null");
            return (Criteria) this;
        }

        public Criteria andDictStatusIsNotNull() {
            addCriterion("dict_status is not null");
            return (Criteria) this;
        }

        public Criteria andDictStatusEqualTo(Integer value) {
            addCriterion("dict_status =", value, "dictStatus");
            return (Criteria) this;
        }

        public Criteria andDictStatusNotEqualTo(Integer value) {
            addCriterion("dict_status <>", value, "dictStatus");
            return (Criteria) this;
        }

        public Criteria andDictStatusGreaterThan(Integer value) {
            addCriterion("dict_status >", value, "dictStatus");
            return (Criteria) this;
        }

        public Criteria andDictStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("dict_status >=", value, "dictStatus");
            return (Criteria) this;
        }

        public Criteria andDictStatusLessThan(Integer value) {
            addCriterion("dict_status <", value, "dictStatus");
            return (Criteria) this;
        }

        public Criteria andDictStatusLessThanOrEqualTo(Integer value) {
            addCriterion("dict_status <=", value, "dictStatus");
            return (Criteria) this;
        }

        public Criteria andDictStatusIn(List<Integer> values) {
            addCriterion("dict_status in", values, "dictStatus");
            return (Criteria) this;
        }

        public Criteria andDictStatusNotIn(List<Integer> values) {
            addCriterion("dict_status not in", values, "dictStatus");
            return (Criteria) this;
        }

        public Criteria andDictStatusBetween(Integer value1, Integer value2) {
            addCriterion("dict_status between", value1, value2, "dictStatus");
            return (Criteria) this;
        }

        public Criteria andDictStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("dict_status not between", value1, value2, "dictStatus");
            return (Criteria) this;
        }

        public Criteria andDictCreateTimeIsNull() {
            addCriterion("dict_create_time is null");
            return (Criteria) this;
        }

        public Criteria andDictCreateTimeIsNotNull() {
            addCriterion("dict_create_time is not null");
            return (Criteria) this;
        }

        public Criteria andDictCreateTimeEqualTo(Date value) {
            addCriterion("dict_create_time =", value, "dictCreateTime");
            return (Criteria) this;
        }

        public Criteria andDictCreateTimeNotEqualTo(Date value) {
            addCriterion("dict_create_time <>", value, "dictCreateTime");
            return (Criteria) this;
        }

        public Criteria andDictCreateTimeGreaterThan(Date value) {
            addCriterion("dict_create_time >", value, "dictCreateTime");
            return (Criteria) this;
        }

        public Criteria andDictCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("dict_create_time >=", value, "dictCreateTime");
            return (Criteria) this;
        }

        public Criteria andDictCreateTimeLessThan(Date value) {
            addCriterion("dict_create_time <", value, "dictCreateTime");
            return (Criteria) this;
        }

        public Criteria andDictCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("dict_create_time <=", value, "dictCreateTime");
            return (Criteria) this;
        }

        public Criteria andDictCreateTimeIn(List<Date> values) {
            addCriterion("dict_create_time in", values, "dictCreateTime");
            return (Criteria) this;
        }

        public Criteria andDictCreateTimeNotIn(List<Date> values) {
            addCriterion("dict_create_time not in", values, "dictCreateTime");
            return (Criteria) this;
        }

        public Criteria andDictCreateTimeBetween(Date value1, Date value2) {
            addCriterion("dict_create_time between", value1, value2, "dictCreateTime");
            return (Criteria) this;
        }

        public Criteria andDictCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("dict_create_time not between", value1, value2, "dictCreateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_sys_dict
     *
     * @mbggenerated do_not_delete_during_merge Wed Mar 07 14:33:51 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_sys_dict
     *
     * @mbggenerated Wed Mar 07 14:33:51 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}